Makefile

Use conditional variable assignment operator with PG_CONFIG to be able to override pg_config location on command-line, like in pg_qualstat.

 Allow PG_CONFIG value to be found on command-line

---

powa--3.2.0--3.2.1dev.sql
powa--3.2.1dev.sql

We keep the dropped databases, the purpose being to still be able to
access them when they have been dropped. But still, we have to cleanup
after a while. The statements and other collected objects are already
cleaned up after powa.retention. Now we also cleanup the statements from
these databases from powa_statements and powa_qualstats_quals.

Cleanup old databases after the expiration period

---

powa.c

Hello, team
From postgres 11 there is opportunity to specify background worker type by filling bgw_type in BackgroundWorker structure. If bgw_type is empty string then we copy bgw_name into bgw_type. But in _PG_init BackgroundWorker structure is not fully initialized, so it can be garbage in bgw_type field. And this garbage will be shown in backend_type column in pg_stat_activity. We can bypass it by setting bgw_type. We can also use memset to zero BackgroundWorker structure. Then bgw_name value will be copied into bgw_type

Modify bgworker initialization to prevent showing garbage in pg_stat_activity 

---

powa--3.1.0.sql
powa--3.1.1.sql
powa--3.1.2.sql
powa--3.2.0.sql
powa--3.2.1dev.sql
powa--4.0.0beta1.sql

This fixes a copy/pasted silly typo in SQL comments. It doesn't matter in reality, but it keeps throwing my searches of code off :)
As it it's in comments only, there is no functionality change.

Fix typos in SQL comments

---

powa--4.0.0beta1.sql

The change will help to make base_query_all_rels_sample() more efficient for clusters with a lot of relations.

Aggregate relation statistics per database

---

CONTRIBUTORS.md
powa--4.1.2--4.1.3.sql
powa--4.1.3.sql
powa.control

We use 'lock_not_available' error condition in
powa_prevent_concurrent_snapshot() in order to only warn about possible
concurrent snapshot when this is true. (For instance, when default
transaction mode is set to read-only in configuration, we'd previously
get an invalid error message.)

Narrow the error condition in powa_prevent_concurrent_snapshot()

---

powa--4.1.2--4.1.3.sql
powa--4.1.3.sql

Fix #40
This PR fix bugs on  `powa_qualstats_aggregate_constvalues_current`: wrong order by from a copy paste and wrong column name. It also include a rewrite to get rid of LATERAL clause and use window functions. Execution is much more faster between 2 to 600x faster.

Fix powa_qualstats_aggregate_constvalues_current

---

powa--5.0.0dev.sql

Close #60 
All mins_in_range and maxs_in_range should be storage main
The reason is that we want those to be inline in the table, we don't
want to have to fetch them via toast. It's the large records array we
want toasted

Max in main

---

powa--5.0.0dev.sql

The query_id field needs to be explicitly casted when NULL is used as a fallback value.

Fix pg11- pg_stat_activity support

---

.github/workflows/tests.yml
powa--5.0.0dev.sql

And also run ci for pg 9.6 to test this code path.

Fix powa_stat_archiver_src for pg 10-

---

powa--5.0.0--5.0.1dev.sql
powa--5.0.1dev.sql

powa_modules are used for cluster-wide pg_stat datasources and do not support custom datasources.
powa_modules and powa_module_functions got it right and don't have the usual "added_manually" column used to distinguish custom rows, but powa_module_functions had a wrong reference to this column.  Also, powa_module_config was incorrectly created with an added_manually column, and dump was configure using it but the extension install script was incorrectly marking some of the init-time data to be custom.
To fix, get rid of any mention of that column in either the table structure of the dump config.
Thanks to github user guruguruguru for the report.

Fix pg_dump error on powa_module_config

---

powa--5.0.0--5.0.1dev.sql

The function already exists so there should be an "OR REPLACE" clause.

Fix powa_activate_module command in 5.0.0--5.0.1 script

---

powa--5.0.0--5.0.1dev.sql
powa--5.0.1dev.sql

That function wasn't modified to properly handle schema qualification for the pg_track_settings-specific queries.
Thanks to Thomas Reiss for the report.

Fix pg_track_settings in powa_delete_and_purge_server()

---

powa--5.0.2.sql

This is to work around the use case of someone importing a bunch of servers at the same time: when this occurs, all those servers are going to coalesce at about the same time, then purge at about the same time, which may saturate IOs
By adding the srvid to the modulo, servers created in sequence will end up offset by 1 for their coalesces/purges. Their first ever coalesced records will be smaller, but I don't see how it would end up being a problem

Smooth out the coalesces and purges

---

.github/powa-archivist.toml.template
.github/workflows/tests.yml

The CI now installs pg_validate_extupgrade, and calls it comparing the current version (retrieved from the control file) and the previous version (retrieved from extension update files).  If no update path exists (which can happen with a new X.0.0 version), the skip is checked.

ci: Check extension install vs upgrade

---

powa--5.0.1--5.0.2.sql
powa--5.0.2.sql

- the view exists in all postgres versions supported by powa
- the "reply_time" column was added in pg12
- a bunch of column renamed and added in pg10

Fix pg_stat_replication compatibility on older pg versions

---

expected/02_remote_api.out
powa--5.0.1--5.0.2.sql
powa--5.0.2.sql

Thanks to github user jw1u1 for the report.
While at it, also fix the function to return whether a remote server has been removed, as the previous code was mistakenly returning whether pg_track_settings is installed.

Fix powa_delete_and_purge_server to also purge *_src_tmp tables

---

powa.c

Upstream commit postgres/postgres@3691edf changed pg_attribute_noreturn() to pg_noreturn macro.

Fix compatibility with pg18

---

.github/workflows/powa_archivist.yml

The underlying script relies on the release already existing to pick the correct version.

ci: Trigger build of powa-archivist on new release, not new tag

---

CONTRIBUTORS.md
powa--5.0.2--5.0.3.sql
powa--5.0.3.sql

The txid_current() function returns a bigint, which cannot fit in a xid.  Since we need the current transaction id to compare it with other fields that are also declared as xid (and since it's not really possible to upgrade an xid to an xid8), downgrade the value returned by txid_current() to an actual xid.
Postgres 13 and above provides an easy way to do that using xid(xid8) and the new pg_current_xact_id() that returns an xid8.  On older version, simulate the same thing by dropping the 4 most significant bits (which hold the epoch) from the returned bigint.
Thanks to github user Nickuru for the report.

Fix txid_current() usage when FullXactId > max xid

---

expected/01_general.out
sql/01_general.sql

As pointed out by Marc Cousin during the review of the last commit, the checks for the STORAGE MAIN should be based on columns named either "mins_in_range" or "maxs_in_range", but it was testing columns name cnotaining "mins" or "maxs". This has been harmless for now but better to fix it in case someone uses those pattern for something else in some powa relation.

Fix non restrictive enough test in 01_general

---

powa--5.0.2--5.0.3.sql
powa--5.0.3.sql

Remove extraneous newlines, whitespaces, use usual -- style comments and add usual "end of" function name comment.

Minor stylistic changes for 4249943

---

expected/01_general.out
powa--5.0.2--5.0.3.sql
powa--5.0.3.sql
sql/01_general.sql

This functions retrieves all the pg_stat_activity sampled rows for the given server (either remote or local) in the given interval.
Per request from Marc Cousin.

coAdd a new powa_stat_get_activity(srvid, from, to)

---

powa--5.0.3--5.1.0.sql
powa--5.1.0.sql

Replace multiple indexes on the *_current(srvid) to include the columns used in the aggregate functions

Improve indexes on *_current tables

---

powa--5.0.3--5.1.0.sql
powa--5.1.0.sql

Some of the newly introduced tables didn't have the needed filtering in pg_extension_config_dump() to ignore rows inserted at CREATE EXTENSION time.

Fix powa compatibility with pg_dump
